version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/got-lost-db
      SPRING_DATASOURCE_USERNAME: hahrens
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: got-lost-db
      POSTGRES_USER: hahrens
      POSTGRES_PASSWORD:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: