# Use a base image with JDK
FROM eclipse-temurin:23

# Set the working directory
WORKDIR /got-lost

# Copy the built JAR file into the container
COPY target/got-lost-0.0.1.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]