spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: got-lost-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or create, create-drop, validate based on your needs
      show-sql: true      # to show SQL queries in logs
    database: postgresql